### ISSUE TITLE
AttributeError: 'SMPLOutput' object has no attribute 'v_posed'

### ISSUE THREAD

**Issue by hh0525** [computational-imaging/GSM#3]
I run this code: python gen_interpolation.py --network xxxx.pkl --outdir xxxx --z_seeds 251,58 but I get a error:
```
Setting up PyTorch plugin "bias_act_plugin"... Done.
Setting up PyTorch plugin "upfirdn2d_plugin"... Done.
Traceback (most recent call last):
  File "/home/huhao/unnamed/GSM/main/gsm/gen_interpolation.py", line 124, in <module>
    generate_video() # pylint: disable=no-value-for-parameter
  File "/home/huhao/miniconda3/envs/3DGS/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/huhao/miniconda3/envs/3DGS/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/huhao/miniconda3/envs/3DGS/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/huhao/miniconda3/envs/3DGS/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/huhao/miniconda3/envs/3DGS/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/huhao/miniconda3/envs/3DGS/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/huhao/unnamed/GSM/main/gsm/gen_interpolation.py", line 118, in generate_video
    generate_one_video(z_seeds, G, c, outdir, truncation_cutoff=truncation_cutoff, truncation_psi=truncation_psi)
  File "/home/huhao/unnamed/GSM/main/gsm/gen_interpolation.py", line 49, in generate_one_video
    image = G.synthesis(ws=ws, c=c, noise_mode='const')["image"][0]
  File "<string>", line 370, in synthesis
  File "/home/huhao/unnamed/GSM/main/gsm/gaussian_renderer/__init__.py", line 30, in render
    means3D = pc.get_xyz(cache_deformation_output=True, use_cached=False, **deformation_kwargs)
  File "/home/huhao/unnamed/GSM/main/gsm/scene/gaussian_model_tets.py", line 476, in get_xyz
    deformation_output = deform_gaussians(self, self.deformer, smpl_kwargs)
  File "/home/huhao/miniconda3/envs/3DGS/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/huhao/unnamed/GSM/main/gsm/deformer/__init__.py", line 186, in deform_gaussians
    smpl_out, deformation_outputs = deformer.run(
  File "/home/huhao/unnamed/GSM/main/gsm/deformer/smpl_deformer.py", line 128, in run
    raise e
  File "/home/huhao/unnamed/GSM/main/gsm/deformer/smpl_deformer.py", line 122, in run
    v_posed = output.v_posed
AttributeError: 'SMPLOutput' object has no attribute 'v_posed'
```

**Comment by MrTornado24** [comment]
Hi, you may forget to do this:
```cd submodules/smplx; python setup.py develop```
